server:
  port: 8900
spring:
  application:
    name: order-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


service:
  store:
     domain: http://localhost:8700