server:
  port: 8900
spring:
  application:
    name: order-service
  config:
    activate:
      on-profile: local, dev, local
    import: optional:configserver:http://localhost:8888
  # h2 settings
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order-service;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    # Bean이 생성되기 전에 ddl 실행
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG